### ISSUE TITLE
Pinned requests requirement

### ISSUE THREAD

**Issue by MartinHjelmare** [exxamalte/python-geojson-client#5]
Hi! Please loosen the version requirement of requests. If possible just require requests, but a minimum version is ok too.

Pinning requirements in libraries complicates things for apps, like home assistant, that use this library, eg if the apps need a higher version.

https://github.com/exxamalte/python-geojson-client/blob/master/setup.py#L10

**Comment by exxamalte** [comment]
Good point. Let me take a quick look at what minimum requirements this library actually has.

**Comment by exxamalte** [comment]
Alright, I went with a minimum version for `requests` and other libraries I use here. I saw that Home Assistant just updated to the same `requests` version.
